spring:
  application:
    name: CodeHub
  datasource:
    url: jdbc:postgresql://localhost:5432/codehub
    username: postgres
    password: 123456
  flyway:
    enabled: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8080